[package]
name = "polkadot-overseer-gen"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
description = "Generate an overseer including builder pattern and message wrapper from a single struct."

[dependencies]
tracing = "0.1"
futures = "0.3"
async-trait = "0.1"
thiserror = "1"
overseer-gen-proc-macro = { package = "polkadot-overseer-gen-proc-macro", path = "./proc-macro" }
metered = { package = "metered-channel", path = "../../metered-channel" }
# trait SpawnNamed
sp-core = { git = "https://github.com/paritytech/substrate", branch = "master" }


[dev-dependencies]
trybuild = "1.0.41"
